rpc_nodes:
  ETH: https://ethereum.blockpi.network/v1/rpc/4ca6dcb6a65b915676a8f0b7246a4839086c6dd7
  BNB: https://bsc.blockpi.network/v1/rpc/fd303b11fdecc129a8643be5b02e906ff60cc7ec
  BSC: https://bsc.blockpi.network/v1/rpc/fd303b11fdecc129a8643be5b02e906ff60cc7ec
  Polygon: https://polygon.blockpi.network/v1/rpc/cba1fadbf0465a1dc9f95a580080fd03c3c52317
  Arbitrum: https://arbitrum.blockpi.network/v1/rpc/06fc11fe0c1506d90d753ba9eb9bd068e66fc7e8
  Optimism: https://optimism.blockpi.network/v1/rpc/db6c0d4fff9c226da0b81e087e3ba1515aa03947
  Base: https://base.blockpi.network/v1/rpc/d8e6b346862da1b94601e3bd36cb6116f69f33d0
  Mantle: https://mantle.blockpi.network/v1/rpc/1772564b1afb6eedf9d1da020a5154c3d9be3ce9
  Avalanche: https://avalanche.blockpi.network/v1/rpc/efe43c4ff7e1956191b103713c5f3c1b83a26939
  TRON: https://rpc.ankr.com/http/tron
  Linea: https://linea.blockpi.network/v1/rpc/c4de080fa5e26e95c1f4a5270f0a60d559cdc807
  Near: https://near.blockpi.network/v1/rpc/a1eb4a0751b8269240ada389f42f37602d8fe8b8

git_bash_path: D:\Git\usr\bin\bash.exe

cast_path: /c/Users/mashiro/.foundry/bin/cast.exe
