rpc_nodes:
  ETH: https://rpc.ankr.com/eth
  BNB: https://rpc.ankr.com/bsc
  BSC: https://rpc.ankr.com/bsc
  Polygon: https://rpc.ankr.com/polygon
  Arbitrum': https://rpc.ankr.com/arbitrum
  Optimism: https://rpc.ankr.com/optimism
  Avalanch: https://rpc.ankr.com/avalanche
  Base: https://rpc.ankr.com/base
  Mantle: https://rpc.ankr.com/mantle
  Avalanche: https://rpc.ankr.com/avalanche
  TRON: https://rpc.ankr.com/http/tron