rpc_nodes:
  ETH: https://rpc.ankr.com/eth
  BSC: https://rpc.ankr.com/bsc
  Polygon: https://rpc.ankr.com/polygon
  Arbitrum: https://rpc.ankr.com/arbitrum
  Optimism: https://rpc.ankr.com/optimism
  Base: https://rpc.ankr.com/base
  Mantle: https://rpc.ankr.com/mantle
  Avalanche: https://rpc.ankr.com/avalanche
  TRON: https://rpc.ankr.com/http/tron
  Blast: https://rpc.ankr.com/blast
  Gnosis: https://rpc.ankr.com/gnosis
  FTM: https://rpc.ankr.com/fantom
  Moonbeam: https://rpc.ankr.com/moonbeam


git_bash_path: D:\Git\usr\bin\bash.exe

cast_path: /c/Users/mashiro/.foundry/bin/cast.exe
